# Generated by Django 3.2.25 on 2024-08-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=60)),
                ('work_type', models.TextField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('fullstack', 'fullstack')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='addUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('who_you_are_description', models.TextField()),
                ('your_experience_1', models.CharField(max_length=20)),
                ('your_experience_2', models.CharField(max_length=20)),
                ('your_experience_3', models.CharField(max_length=20)),
                ('your_frontend_framework_1', models.CharField(max_length=20)),
                ('your_frontend_framework_2', models.CharField(max_length=20)),
                ('your_backend_framework_1', models.CharField(max_length=20)),
                ('your_backend_framework_2', models.CharField(max_length=20)),
                ('your_fullstack_framework_1', models.CharField(max_length=20)),
                ('your_fullstack_framework_2', models.CharField(max_length=20)),
                ('your_specialty', models.TextField()),
                ('testimony', models.TextField()),
                ('testimony_sharer', models.CharField(max_length=255)),
                ('testimony_rating', models.IntegerField()),
                ('testimony_sharer_position', models.CharField(max_length=255)),
                ('frequently_asked_question_1', models.TextField()),
                ('frequently_asked_question_answer_1', models.TextField()),
                ('frequently_asked_question_2', models.TextField()),
                ('frequently_asked_question_answer_2', models.TextField()),
                ('frequently_asked_question_3', models.TextField()),
                ('frequently_asked_question_answer_3', models.TextField()),
                ('your_address', models.CharField(max_length=255)),
                ('your_contact', models.CharField(max_length=255)),
                ('your_email', models.EmailField(max_length=255)),
                ('your_previous_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
            ],
        ),
    ]
